### ISSUE TITLE
Decimal base used to represent a byte

### ISSUE THREAD

**Issue by S-Stanley** [mschwartz/assembly-tutorial#4]
Hello! I'm currently learning assembly with your repository, and I have a small question:

At line [47](https://github.com/mschwartz/assembly-tutorial/blob/main/README.md?plain=1#L47) and [54](https://github.com/mschwartz/assembly-tutorial/blob/main/README.md?plain=1#L54) you did use a decimal base to represent a byte. Is it on purpose? If so, why didn't you use a binary base (e.g. `11010001`)?

**Comment by mschwartz** [comment]
Those are the bit numbers.  There are 8bits to a byte, numbered bit0 to bit7.  

In your example, 11010001, bits 0, 4, 6, and 7 are set.

**Comment by S-Stanley** [comment]
Thanks for your answer, I understand better! I'm closing the issue
