### ISSUE TITLE
off-by-one problem

### ISSUE THREAD

**Issue by snakeru** [mschwartz/assembly-tutorial#9]
There are two off-by-one bugs at the end of "Boolean Algebra" section:

> A great use of the AND operator is to do a modulo of a number to a power of 2. For example, AND with 3 gets you a result between 0 and 2. AND with 7 gets you a result between 0 and 8.

**Comment by mschwartz** [comment]
Pull request is welcomed!

**Comment by snakeru** [comment]
Apparently GitHub allows web-only PR creation. There you go:

https://github.com/mschwartz/assembly-tutorial/pull/10
